import { prisma } from "../../services/prisma";
import { logger } from "../../services/logger";

export type XrayInboundOption = { id: number; port?: number; protocol?: string; remark?: string; tag?: string; nodeId?: number | string; enable?: boolean; enabled?: boolean };
const XRAY_TIMEOUT_MS = 10_000;
const GB = 1024n * 1024n * 1024n;
export function gbToBytes(gb: number) { return BigInt(gb) * GB; }
export function maskToken(token?: string | null) { return token ? `${"*".repeat(Math.max(token.length - 4, 8))}${token.slice(-4)}` : "—"; }
export function sanitizePanelError(error: unknown) { return error instanceof Error ? error.message.replace(/Bearer\s+\S+/gi, "Bearer ********") : String(error); }
export function xrayInboundSnapshot(inbounds: XrayInboundOption[], selectedIds: number[]) {
  const selected = new Set(selectedIds);
  return JSON.stringify(inbounds.filter((inbound) => selected.has(inbound.id)).map(({ id, remark, protocol, port, tag, nodeId }) => ({ id, remark, protocol, port, tag, nodeId })));
}
export function formatXrayBytes(value?: bigint | number | string | null) {
  const bytes = typeof value === "bigint" ? Number(value) : Number(value ?? 0);
  if (!Number.isFinite(bytes) || bytes <= 0) return "0 GB";
  return `${(bytes / (1024 ** 3)).toFixed(2)} GB`;
}
function normalizeBaseUrl(url: string) { const parsed = new URL(url.trim()); if (!["http:", "https:"].includes(parsed.protocol)) throw new Error("آدرس پنل باید http یا https باشد"); return parsed.toString().replace(/\/+$/, ""); }
async function request<T>(path: string, init: RequestInit = {}, config?: { apiBaseUrl: string; apiToken: string }): Promise<T> { const panel = config ?? await XrayPanelService.getEnabledConfig(); if (!panel) throw new Error("اتصال پنل Xray فعال نیست"); const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), XRAY_TIMEOUT_MS); try { const response = await fetch(`${normalizeBaseUrl(panel.apiBaseUrl)}${path}`, { ...init, signal: controller.signal, headers: { "Content-Type": "application/json", Authorization: `Bearer ${panel.apiToken}`, ...(init.headers ?? {}) } }); const text = await response.text(); const json = text ? JSON.parse(text) : {}; if (!response.ok || json.success === false) throw new Error(json.msg || json.message || `HTTP ${response.status}`); return json as T; } finally { clearTimeout(timeout); } }
export class XrayPanelService { static async getEnabledConfig() { return prisma.xrayPanelConfig.findFirst({ where: { enabled: true }, orderBy: { updatedAt: "desc" } }); } static async upsertConfig(data: { apiBaseUrl: string; apiToken: string; subscriptionBaseUrl?: string; enabled?: boolean }) { const existing = await prisma.xrayPanelConfig.findFirst({ where: { name: "default" } }); const payload = { ...data, apiBaseUrl: normalizeBaseUrl(data.apiBaseUrl) }; return existing ? prisma.xrayPanelConfig.update({ where: { id: existing.id }, data: payload }) : prisma.xrayPanelConfig.create({ data: { name: "default", ...payload } }); } static async testConnection() { const config = await this.getEnabledConfig(); if (!config) throw new Error("تنظیمات فعال پنل پیدا نشد"); try { const inbounds = await XrayClientService.listInbounds(config); await prisma.xrayPanelConfig.update({ where: { id: config.id }, data: { lastSuccessAt: new Date(), lastError: null, lastInboundCount: inbounds.length } }); logger.info("XRAY_PANEL_TEST_SUCCESS", { inboundCount: inbounds.length }); return { ok: true, inboundCount: inbounds.length }; } catch (error) { const message = sanitizePanelError(error); await prisma.xrayPanelConfig.update({ where: { id: config.id }, data: { lastError: message } }); logger.error("XRAY_PANEL_TEST_FAILED", { error: message }); return { ok: false, error: message, inboundCount: 0 }; } } }
export class XrayClientService { static async listInbounds(config?: { apiBaseUrl: string; apiToken: string }) { const res = await request<{ obj?: XrayInboundOption[] }>("/panel/api/inbounds/options", {}, config); const inbounds = (res.obj ?? []).filter((inbound) => inbound.enabled !== false && inbound.enable !== false); logger.info("XRAY_INBOUNDS_FETCHED", { count: inbounds.length }); return inbounds; } static async createClient(input: { email: string; trafficBytes: bigint; expiresAt: Date; telegramId: string | number; inboundIds: number[] }) { logger.info("XRAY_CLIENT_CREATE_REQUEST", { email: input.email, inboundIds: input.inboundIds }); const res = await request<{ obj?: { id?: string; uuid?: string; subId?: string } }>("/panel/api/clients/add", { method: "POST", body: JSON.stringify({ client: { email: input.email, totalGB: Number(input.trafficBytes) / Number(GB), expiryTime: input.expiresAt.getTime(), tgId: Number(input.telegramId), limitIp: 0, enable: true }, inboundIds: input.inboundIds }) }); logger.info("XRAY_CLIENT_CREATED", { email: input.email }); return res.obj ?? {}; } static async updateClient(email: string, input: { totalBytes: bigint; expiresAt: Date; telegramId: string | number }) { logger.info("XRAY_CLIENT_RENEW_REQUEST", { email }); try { const res = await request<{ obj?: unknown }>(`/panel/api/clients/update/${encodeURIComponent(email)}`, { method: "POST", body: JSON.stringify({ email, totalGB: Number(input.totalBytes) / Number(GB), expiryTime: input.expiresAt.getTime(), tgId: Number(input.telegramId), enable: true }) }); logger.info("XRAY_CLIENT_RENEW_SUCCESS", { email }); return res.obj; } catch (error) { logger.error("XRAY_CLIENT_RENEW_FAILED", { email, error: sanitizePanelError(error) }); throw error; } } static getClient(email: string) { return request<{ obj?: any }>(`/panel/api/clients/get/${encodeURIComponent(email)}`); } static links(email: string) { return request<{ obj?: any }>(`/panel/api/clients/links/${encodeURIComponent(email)}`).then((r) => { logger.info("XRAY_CLIENT_LINKS_FETCHED", { email }); return r.obj; }).catch((e) => { logger.warn("XRAY_CLIENT_LINKS_FAILED", { email, error: sanitizePanelError(e) }); throw e; }); } static traffic(email: string) { return request<{ obj?: any }>(`/panel/api/clients/traffic/${encodeURIComponent(email)}`).then((r) => { logger.info("XRAY_CLIENT_TRAFFIC_FETCHED", { email }); return r.obj; }).catch((e) => { logger.warn("XRAY_CLIENT_TRAFFIC_FAILED", { email, error: sanitizePanelError(e) }); throw e; }); } }
