export const BOT_TIME_ZONE = "Asia/Tehran";
export const PERSIAN_MONTH_NAMES = ["فروردین", "اردیبهشت", "خرداد", "تیر", "مرداد", "شهریور", "مهر", "آبان", "آذر", "دی", "بهمن", "اسفند"];
const breaks = [-61,9,38,199,426,686,756,818,1111,1181,1210,1635,2060,2097,2192,2262,2324,2394,2456,3178];
function div(a:number,b:number){return ~~(a/b)}
function jalCal(jy:number){let bl=breaks.length, gy=jy+621, leapJ=-14,jp=breaks[0],jm=0,jump=0,n=0,i=1;if(jy<jp||jy>=breaks[bl-1])throw new Error("Invalid Jalali year");for(;i<bl;i++){jm=breaks[i];jump=jm-jp;if(jy<jm)break;leapJ+=div(jump,33)*8+div(jump%33,4);jp=jm}n=jy-jp;leapJ+=div(n,33)*8+div((n%33)+3,4);if(jump%33===4&&jump-n===4)leapJ++;const leapG=div(gy,4)-div((div(gy,100)+1)*3,4)-150;const march=20+leapJ-leapG;if(jump-n<6)n=n-jump+div(jump+4,33)*33;let leap=((n+1)%33)-1;if(leap===-1)leap=4;return{leap,gy,march}}
function g2d(gy:number,gm:number,gd:number){let d=div((gy+div(gm-8,6)+100100)*1461,4)+div(153*((gm+9)%12)+2,5)+gd-34840408;d=d-div(div(gy+100100+div(gm-8,6),100)*3,4)+752;return d}
function d2g(jdn:number){let j=4*jdn+139361631;j=j+div(div(4*jdn+183187720,146097)*3,4)*4-3908;const i=div((j%1461),4)*5+308;const gd=div((i%153),5)+1;const gm=((div(i,153)%12)+1);const gy=div(j,1461)-100100+div(8-gm,6);return{gy,gm,gd}}
function d2j(jdn:number){const gy=d2g(jdn).gy;let jy=gy-621;const r=jalCal(jy);const jdn1f=g2d(gy,3,r.march);let k=jdn-jdn1f;if(k>=0){if(k<=185)return{jy,jm:1+div(k,31),jd:(k%31)+1};k-=186}else{jy--;k+=179;if(jalCal(jy).leap===0)k++;}return{jy,jm:7+div(k,30),jd:(k%30)+1}}
function gregorianToJalali(gy:number,gm:number,gd:number){return d2j(g2d(gy,gm,gd))}
function fallbackJalaliYear(date:Date,timeZone:string){const parts=new Intl.DateTimeFormat("en-US",{timeZone,year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(date);const val=(t:string)=>Number(parts.find(p=>p.type===t)?.value);return gregorianToJalali(val("year"),val("month"),val("day")).jy}
function isValidJalaliYear(year:number){return Number.isFinite(year)&&Number.isInteger(year)&&year>=1300}
export function isJalaliLeapYear(jy:number){return jalCal(jy).leap===0}
export function jalaliMonthLength(jy:number,jm:number){if(jm<=6)return 31;if(jm<=11)return 30;return isJalaliLeapYear(jy)?30:29}
export function jalaliToGregorian(jy:number,jm:number,jd:number){return d2g(j2d(jy,jm,jd))}
function j2d(jy:number,jm:number,jd:number){const r=jalCal(jy);return g2d(r.gy,3,r.march)+(jm-1)*31-div(jm,7)*(jm-7)+jd-1}
export function zonedJalaliToUtcDate(jy:number,jm:number,jd:number,hour:number,minute:number,timeZone=BOT_TIME_ZONE){const g=jalaliToGregorian(jy,jm,jd);const guess=new Date(Date.UTC(g.gy,g.gm-1,g.gd,hour,minute));const parts=new Intl.DateTimeFormat("en-US",{timeZone,hour12:false,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit"}).formatToParts(guess);const val=(t:string)=>Number(parts.find(p=>p.type===t)?.value);const asUTC=Date.UTC(val("year"),val("month")-1,val("day"),val("hour"),val("minute"),val("second"));return new Date(guess.getTime()-(asUTC-guess.getTime()))}
export function getCurrentJalaliYear(now=new Date(),timezone=BOT_TIME_ZONE):number{let year=Number(new Intl.DateTimeFormat("en-US-u-ca-persian",{timeZone:timezone,year:"numeric"}).formatToParts(now).find(p=>p.type==="year")?.value);if(!isValidJalaliYear(year)){console.error("JALALI_PICKER_INVALID_YEAR",{year,timezone,source:"intl"});year=fallbackJalaliYear(now,timezone)}if(!isValidJalaliYear(year)){console.error("JALALI_PICKER_INVALID_YEAR",{year,timezone,source:"fallback"});return 1400}return year}
export function getSelectableJalaliYears(now=new Date()):number[]{const currentYear=getCurrentJalaliYear(now);const years=[currentYear,currentYear+1,currentYear+2].filter(isValidJalaliYear);if(years.length!==3){console.error("JALALI_PICKER_INVALID_YEAR",{currentYear,years});const safe=getCurrentJalaliYear(now,BOT_TIME_ZONE);return [safe,safe+1,safe+2].filter(isValidJalaliYear).slice(0,3)}return years}
export const currentJalaliYear = getCurrentJalaliYear;
export function formatJalaliDateTime(date:Date,timeZone=BOT_TIME_ZONE){
  const parts=new Intl.DateTimeFormat("fa-IR-u-ca-persian",{timeZone,year:"numeric",month:"long",day:"numeric",hour:"2-digit",minute:"2-digit",hour12:false}).formatToParts(new Date(date));
  const val=(t:string)=>parts.find(p=>p.type===t)?.value ?? "";
  return `${val("day")} ${val("month")} ${val("year")} ساعت ${val("hour")}:${val("minute")}`;
}
export function formatPredictionCountdown(closesAt:Date,now=new Date()){const ms=new Date(closesAt).getTime()-now.getTime();if(ms<=0)return "مهلت تمام شده";const totalMinutes=Math.ceil(ms/60000);const days=Math.floor(totalMinutes/1440);const hours=Math.floor((totalMinutes%1440)/60);const minutes=totalMinutes%60;const out:string[]=[];if(days)out.push(`${days.toLocaleString("fa-IR")} روز`);if(hours)out.push(`${hours.toLocaleString("fa-IR")} ساعت`);if(minutes||!out.length)out.push(`${minutes.toLocaleString("fa-IR")} دقیقه`);return out.join(" و ");}
