export const uiIcons = {
  home: "🏠",
  product: "📦",
  account: "👤",
  wallet: "💳",
  coupon: "🎟",
  support: "🆘",
  guide: "📘",
  admin: "🛠",
  dashboard: "📊",
  inventory: "📥",
  xray: "🧩",
  users: "👥",
  payments: "💳",
  settings: "⚙️",
  broadcast: "📣",
  invoice: "🧾",
  info: "🔍",
  refresh: "🔄",
  success: "✅",
  active: "🟢",
  pending: "🟡",
  danger: "🔴",
  disabled: "⚫",
  warning: "⚠️",
  error: "❌",
  back: "↩️",
  cancel: "❌",
  cart: "🛒",
  link: "🔗",
  configs: "📋",
  renew: "♻️",
  repair: "🛠",
  cleanup: "🧹",
} as const;

export type UiIconName = keyof typeof uiIcons;
